### ISSUE TITLE
Legend Title

### ISSUE THREAD

**Issue by Btibert3** [briatte/ggnet#18]
I am probably missing something obvious, but is is possible to remove the legend title and just show the legend values when using the parameter `color`?

For context, I was thinking something along the lines of 

```
ggnet2(g, 
       color = "ntype", 
       palette = col, 
       mode = "fruchtermanreingold", 
       alpha=.7, 
       legend.position = "bottom", 
       legend.title=element_blank())
```

**Comment by briatte** [comment]
Yes, that's possible if you 'externalize' the `legend.title` argument, since it has to go in `theme` to work:

``` R
library(GGally)
library(ggplot2)
library(network)

g = network(sna::rgraph(10))
g %v% "ntype" = sample(1:2, 10, replace = TRUE)
col = c("1" = "gold", "2" = "tomato")

ggnet2(g, 
       color = "ntype", 
       palette = col, 
       mode = "fruchtermanreingold", 
       alpha=.7, 
       legend.position = "bottom") +
  theme(legend.title=element_blank())
```

![](https://cloud.githubusercontent.com/assets/322533/14552894/82635250-02e2-11e6-82ed-5bf242a4b25d.png)

I would like to recommend that you try [ggnetwork](https://github.com/briatte/ggnetwork): its syntax is closer to that of ggplot2 than is the case for ggnet2. Take a look at [the package vignette](https://briatte.github.io/ggnetwork/) for examples.
