### ISSUE TITLE
Use approach in NetworkX for arrows

### ISSUE THREAD

**Issue by aterhorst** [briatte/ggnet#24]
Hi. The arrow gap workaround is not working for me. I have different node sizes so a standard arrow gap is not helpful. 

I was wondering if ggnet could not implement something similar to what is used in NetworkX? This is a python package for network analysis. Essentially this uses a line stub instead of an arrow.  The aesthetics can be made to look nice like the examples in http://cxhernandez.com/tutorials/networks/2015/03/29/shortest-path.html

**Comment by briatte** [comment]
Thanks for the suggestion, @aterhorst -- I am familiar with NetworkX but was not familiar with the examples you link to.

You can already implement the trick used in the example by having two edges on top of one another (that trick is easier to implement with [`ggnetwork`](https://github.com/briatte/ggnetwork). However, the problem would remain that the stubs would be of different length depending on node size.

Unless I find a way to measure [actual](https://stackoverflow.com/questions/17311917/ggplot2-the-unit-of-size) instead of relative node size, I am stuck, for now, with the current behaviour of `ggnet`. It's on my top-3 list of improvements.

**Comment by aterhorst** [comment]
Thanks. What they do is measure stub length as proportion of edge length e.g. 1:10. So longer edges have longer stubs. I think it is conditioned on node size as well.

## 

Andrew Terhorst
Open Innovation Researcher
Location leader for Sandy Bay site

DATA61 |  CSIRO
E andrew.terhorst@csiro.au T +61 3 6237 5662 M +61 400 869 594
15 College Rd, Sandy Bay, TAS 7005
http://www.data61.csiro.au
http://people.csiro.au/T/A/Andrew-Terhorst.aspx

**Comment by briatte** [comment]
I haven't looked into `grid` long enough to find out how big the points are in the corresponding geom—but I know it's pretty complex to sort out… which is why this improvement is not yet there.

I'm going to ask @hadley in case there is a simple answer:

Dear Hadley, if I draw a `geom_segment` that ends at (xend, yend) and there is another `geom_point` drawn there at a given size, is there an easy way to stop drawing the segment just before it intersects with the point?

**Comment by hadley** [comment]
Not that I know of

**Comment by briatte** [comment]
Closing this, as I won't revisit the code to solve the 'arrow gap' issue better than it is.

As mentioned above, [`ggnetwork`](https://github.com/briatte/ggnetwork) should give slightly better results on that issue, but the best solution is almost certainly to use [`ggraph`](https://github.com/thomasp85/ggraph).

Thanks to Andrew and Hadley for their contributions.
