### ISSUE TITLE
Moving node labels

### ISSUE THREAD

**Issue by andreabduque** [briatte/ggnet#28]
Hello,
is there an option to move node labels from the center of the node?
I'd like to put them under the nodes because my labels are too big!
Thank you!

**Comment by briatte** [comment]
Hi @andreabduque 

All apologies for leaving your question unanswered for so long.

The answer to issue #34 applies here: you will need a more advanced network plotting function to do that, in order to use [`ggrepel`](https://cran.r-project.org/package=ggrepel) on your node labels. 

The magic of `ggrepel` can be applied to network visualization using either my other network visualization function, [`ggnetwork`](https://github.com/briatte/ggnetwork) (see the [relevant part of the vignette](https://briatte.github.io/ggnetwork/#geom_nodetext_repel-and-geom_nodelabel_repel)), or the even more powerful and flexible [`ggraph`](https://github.com/thomasp85/ggraph) package. (Copied from #34).

Hope this helps!
