### ISSUE TITLE
citing this work

### ISSUE THREAD

**Issue by tcgriffith** [briatte/ggnet#29]
how should I cite this work if I want to use it? thanks!

**Comment by briatte** [comment]
Hi @tcgriffith 

Thanks for asking, and all apologies for answering your question very, very late… !

The `ggnet` function is part of the [`GGally` package](), so that's what should be cited if need be. The package [is on CRAN](https://cran.r-project.org/package=GGally) and [its repository](https://github.com/ggobi/ggally/) shows the DOI for it.
