### ISSUE TITLE
Set number of rows in legend

### ISSUE THREAD

**Issue by davidvilanova** [briatte/ggnet#33]
Hi ,
to avoid cross posting i added a question on ggnet2.

https://stackoverflow.com/questions/52094754/modify-the-number-of-rows-in-the-legend-of-a-plot

**Comment by briatte** [comment]
Hi @davidvilanova 

Thanks for posting this here, and sorry for not answering earlier.

Your issue is related to how `ggplot2` handles legends: I cannot fix it by modifying `ggnet`.

Please let me know if you find a solution, although I agree with the comment on your StackOverflow question, you probably have too many colour groups in that graph!
